### ISSUE TITLE
RTC info in VDP Protocol doesn't actually fit

### ISSUE THREAD

**Issue by stevesims** [breakintoprogram/agon-vdp#91]
The 4th byte in the RTC data packet is the "day of year" - that _should_ be a value in the range 0-365 - but we're sending an 8-bit value there, so it's limited to the range 0-255.  This is a bug.  😁 

To fix this we need to change the protocol either to send the day of year as 2 bytes or to adopt a bit from one of the other bytes that get sent across.

**Comment by breakintoprogram** [comment]
This has been fixed in the following commits:

- https://github.com/breakintoprogram/agon-vdp/commit/b1e06c34fbbbfe3d9ec6ee1da0e7d086769b4dff
- https://github.com/breakintoprogram/agon-mos/commit/ecda7a50e59cc47320071a8686d47ee54e4a52e7
- https://github.com/breakintoprogram/agon-mos/commit/9a0de3c235a9a85fc52e4022fbfad599ed9df530

**Comment by stevesims** [comment]
nice 👍
